export const MODULES_SEED = [
  {
    title: 'Mindset Vibe Coding',
    slug: 'intro-vibe-coding',
    description: 'Kenalan dengan cara baru ngoding — tanpa harus jadi programmer dulu.',
    youtubeUrl: 'https://youtu.be/g2ykOVfJXyo',
    gammaUrl: 'https://gamma.app/embed/y7h9hlo7sb7mjdv',
    parentIds: [],
    orderIndex: 0,
  },
  {
    title: 'Setup Lingkungan Kerja',
    slug: 'setup-lingkungan-kerja',
    description: 'Install semua yang dibutuhkan: VS Code, Node.js, Claude Code.',
    youtubeUrl: null,
    gammaUrl: 'https://gamma.app/embed/x3z6x4xgtr2v28z',
    parentIds: ['intro-vibe-coding'],
    orderIndex: 1,
  },
  {
    title: 'Prompt Engineering Dasar',
    slug: 'prompt-engineering-dasar',
    description: 'Cara ngomong ke AI supaya hasilnya sesuai keinginan.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['intro-vibe-coding'],
    orderIndex: 2,
  },
  {
    title: 'Bikin Web App Pertama',
    slug: 'web-app-pertama',
    description: 'Dari nol sampai jalan — web app sederhana dengan Next.js.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['setup-lingkungan-kerja', 'prompt-engineering-dasar'],
    orderIndex: 3,
  },
  {
    title: 'Deploy ke Internet',
    slug: 'deploy-ke-internet',
    description: 'Supaya orang lain bisa pakai aplikasimu — deploy ke Vercel.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['web-app-pertama'],
    orderIndex: 4,
  },
  {
    title: 'Koneksi Database',
    slug: 'koneksi-database',
    description: 'Simpan data user dengan Supabase — tanpa ribet.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['web-app-pertama'],
    orderIndex: 5,
  },
  {
    title: 'Monetisasi Produk Digital',
    slug: 'monetisasi-produk-digital',
    description: 'Integrasikan payment gateway dan mulai jual produk.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['deploy-ke-internet', 'koneksi-database'],
    orderIndex: 6,
  },
]
