export const MODULES_SEED = [
  {
    title: 'Mindset Vibe Coding',
    slug: 'intro-vibe-coding',
    description: 'Kenalan dengan cara baru ngoding — tanpa harus jadi programmer dulu.',
    youtubeUrl: 'https://youtu.be/g2ykOVfJXyo',
    gammaUrl: 'https://drive.google.com/file/d/1CSR08CezZFAr2MT3mQu-I0iME7qPWNry/preview',
    parentIds: [],
    orderIndex: 0,
  },
  {
    title: 'Pentingnya Logika yang Benar Saat Membuat Project',
    slug: 'setup-lingkungan-kerja',
    description: 'Install semua yang dibutuhkan: VS Code, Node.js, Claude Code.',
    youtubeUrl: null,
    gammaUrl: 'https://drive.google.com/file/d/121iyc9NxHddM8SEKeqtTIemrxWQlPnL9/preview',
    parentIds: ['intro-vibe-coding'],
    orderIndex: 1,
  },
  {
    title: 'Cara Instal VS Code, Claude Code dan Membeli Akun Pro Claude',
    slug: 'prompt-engineering-dasar',
    description: 'Cara ngomong ke AI supaya hasilnya sesuai keinginan.',
    youtubeUrl: 'https://youtu.be/7PpoNa2d4w4',
    gammaUrl: null,
    parentIds: ['intro-vibe-coding'],
    orderIndex: 2,
  },
  {
    title: 'Cara Menginstal Plugin MCP dan Skill',
    slug: 'web-app-pertama',
    description: 'Dari nol sampai jalan — web app sederhana dengan Next.js.',
    youtubeUrl: 'https://youtu.be/CYL9ZTRRq6U',
    gammaUrl: null,
    parentIds: ['setup-lingkungan-kerja', 'prompt-engineering-dasar'],
    orderIndex: 3,
  },
  {
    title: 'Deploy ke Internet',
    slug: 'deploy-ke-internet',
    description: 'Supaya orang lain bisa pakai aplikasimu — deploy ke Vercel.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['web-app-pertama'],
    orderIndex: 4,
  },
  {
    title: 'Koneksi Database',
    slug: 'koneksi-database',
    description: 'Simpan data user dengan Supabase — tanpa ribet.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['web-app-pertama'],
    orderIndex: 5,
  },
  {
    title: 'Monetisasi Produk Digital',
    slug: 'monetisasi-produk-digital',
    description: 'Integrasikan payment gateway dan mulai jual produk.',
    youtubeUrl: null,
    gammaUrl: null,
    parentIds: ['deploy-ke-internet', 'koneksi-database'],
    orderIndex: 6,
  },
]
